# Generated by Django 3.0.5 on 2020-06-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem_purchased'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('wishlists.add_wishlistitems', 'Add WishListItems'),)},
        ),
    ]
